name: Mirroring

on: [push, pull_request]

env:
  MIRROR_URL: 'git@github.com:Andr0y/sokoban.git'
  EXECUTABLES: 'sokoban'

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          BAD_FILES=$(find . -type f -path "*/tmp/*" -or -name "#*#" -or -name "*~" -or -name "*.o" \
          -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*.gcov" \
          -or -iname "*pain_au_chocolat*")
        
  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_repository_cleanliness
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make
        timeout-minutes: 2
      - run: make clean
      - run: |
          if [ ! -e "$EXECUTABLES" ]
            exit 1
          fi
          
  run_tests:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make tests_run
        timeout-minutes: 2
        
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
