name: Mirroring

on: [push, delete]

jobs:
  Mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:Andr0y/sokoban.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
